### ISSUE TITLE
Patient Registration page

### ISSUE THREAD

**Issue by katsanevakis** [swiftss-org/registry-api#10]
As a doctor, I want to register a patient's demographic info

Hospital (from hospital lists)
Name
Patient Hospital ID
National ID (optional)
DoB (Year compulsory, month/day optional )/ Age 
Gender
Phone 1
Phone 2
Address

**Comment by dkoutsonikolis** [comment]
From the Backend side, I have started working on this issue. I am planning on creating the below endpoints:
- GET `/hospitals/`, to retrieve the list of available hospitals
- GET `/hospitals/{id}/`, to retrieve details about a specific hospital
- POST `/patients/`, to register a new patient
- GET `/patients/{id}/`, to retrieve details about a specific patient

For the registration page, I believe Fronted should use the GET `/hospitals/` endpoint to populate the `Center` field and the POST `/patients/` endpoint to actually register a new patient. @whosyourtaco are those endpoints ok for this page?

**Comment by whosyourtaco** [comment]
Yeah, awesome! There are great.
