### ISSUE TITLE
Episode Registration

### ISSUE THREAD

**Issue by dkoutsonikolis** [swiftss-org/registry-api#49]
We should be able to register an episode for an existing patient. 

To do that we should create a `POST` `/episodes/{patient_id}/` endpoint, which would expect as input the following:
- type of episode
- hospital_id, this is the hospital where the episode was registered. To get the possible hospitals, the FE should use the `GET` `/hospitals/` endpoint.
- CEPOD
- Side
- Occurence
- Type
- Complexity
- Comments
-  Mesh Type
- Anaesthetic Type
- Diathermy Used
- surgeon_ids, a list of the ids of the surgeons of the episode (retrieve them through the endpoint described here #48 )

Note: We will validate if there is a `PatientHospitalMapping` entry for the specified Hospital for this patient before registering an episode. If we want to register an episode where there is no `PatientHospitalMapping` entry yet, we should first create one using the POST `patient-hospital-mappings` endpoint.

**Comment by dkoutsonikolis** [comment]
@katsanevakis I have some questions:
1. For the `Surgeons` field, we should use the endpoint described in #48 and the FE should choose only users with certain levels (eg Lead Surgeon, Surgeon, etc.). If yes, could you provide those levels? If not, this means that we should be able to add to the `Surgeons` field any MedicalPersonnel without checking their level(eg add a secretary in the `Surgeons` field)?
2. There is a `comments` field which we have talked about and have already added as a DB field. However, there is an additional free text field `Additional Procedures, Complications` which we have not talked about. Should we add an extra free text field for this one? Is there a reason we need to have two free text fields for an Episode?

**Comment by katsanevakis** [comment]
1.  The current requirements for levels are :
Surgeon
Lead Surgeon 
National Lead 
2. The 1st comment box is for info about the Episode details and the 2nd one for info about the surgery.

3. we could have it as an input in the episode registration page, with current date as default. (there might be the case you want to retroactively add episodes happened in past dates.
4.  Yes
