### ISSUE TITLE
Episode Discharge

### ISSUE THREAD

**Issue by dkoutsonikolis** [swiftss-org/registry-api#50]
We should create a `POST` `/discharge/` endpoint. This endpoint should get as input:

- Episode ID
- Discharge date
- Aware of Mesh
- Infection

Right now we have a `discharge_date` inside the `Episode` model. I believe we should delete it and create a new `Discharge` model which should have an OneToOne FK to the `Episode` table. It should also have two Boolean fields `Aware of Mesh` and `Infection`.

Before actually creating a discharge, we should perform some validations:
- There is no other `Discharge` for this episode
- The `Discharge.date` provided is equal or greater than the `surgery_date` of the related `Episode`

**Comment by dkoutsonikolis** [comment]
@katsanevakis should the `Aware of Mesh` and `Infection` fields be mandatory?

**Comment by katsanevakis** [comment]
Not clear right now. Lets have them optional and change later if needed.
