### ISSUE TITLE
Episode Follow Up

### ISSUE THREAD

**Issue by dkoutsonikolis** [swiftss-org/registry-api#51]
We should create a POST `/follow-ups/` endpoint. This endpoint should get as input:

- Episode ID
- Follow Up date
- attendee_ids, a list of the ids of the attendees of the follow up (retrieve them through the endpoint described here #48 )
- Pain Severity
- Pain Description
- Mesh Awareness
- Seroma
- Infection
- Numbness

All the above fields are mandatory except the `Pain Description`. There should be at least one `Attendee`.

Before adding a Follow Up, we should perform some validations:
- The Follow Up date provided is greater than the `surgery_date` of the related `Episode`.
- A `Discharge` should exist for the related `Episode`(ie the patient should be discharged in order to create a follow up).
- The Follow Up date provided is greater than the `date` of the related `Discharge`.
- No validation takes place between the `date` and the `date` of other `FollowUp` objects for the same `Episode`(e.g. don't allow to register a Follow Up if there is already a Follow Up with greater date). This is so a user is flexible to register Follow Ups without doing it necessarily date ordered.

**Comment by dkoutsonikolis** [comment]
@katsanevakis can we have more than one Follow Ups for the same episode?

**Comment by katsanevakis** [comment]
@dkoutsonikolis yes, therey maybe additional followups for the same episode.
